name: myknott
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^3.0.1
  future_button: ^0.1.2
  connectivity: ^3.0.3
  font_awesome_flutter:
  dio: ^4.0.0-prev2
  firebase_auth: ^1.0.1
  salomon_bottom_bar: ^3.0.0
  firebase_storage: 
  firebase_core: ^1.17.1
  timelines:
  timeline_tile:
  flutter_secure_storage:
  intl:
  
  sliding_up_panel: ^1.0.2
  google_maps_flutter:
  table_calendar:
  cached_network_image:
  cupertino_icons: ^1.0.2
  firebase_messaging: 
  shared_preferences: ^2.0.15
  url_launcher: 
  image_picker: ^0.7.4
  fluttertoast: ^8.0.4
  lazy_load_scrollview: ^1.3.0
  http:
  bubble: ^1.2.1
  emoji_picker_flutter: any
  permission_handler: ^7.0.0
  google_sign_in: 
  flutter_easyloading: ^3.0.0
  flutter_facebook_auth: ^3.2.0
  flutter_svg: ^0.21.0-nullsafety.0
  date_format: ^2.0.4
  carousel_slider: ^4.0.0
  flutter_linkify:
  flutter_datetime_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/userr.png
    - assets/user.png
    - assets/chat.png
    - assets/caller.png
    - assets/location.png
    - assets/logo.png
    - assets/appointment.png
    - assets/appointment1.png
    - assets/brown.jpg
    - assets/Error.png
    - assets/404.svg
    - assets/noUserFound.png

  fonts:
    - family: Whitney
      fonts:
        - asset: fonts/Whitney-Book.otf
